# version format
version: "{build}"

# Operating system (build VM template)
os: Windows Server 2012 R2

# environment variables
environment:
  GOPATH: c:\gopath

# scripts that run after cloning repository
install:
  - set Path=c:\go\bin;%Path%
  - echo %Path%
  - msiexec /x {FF5B30B2-08C2-11E1-85A2-6ACA4824019B} /q
  - appveyor DownloadFile https://storage.googleapis.com/golang/go1.4.1.windows-amd64.msi
  - msiexec /i go1.4.1.windows-amd64.msi /q
  - go version
  - go env
  - mkdir c:\gopath
  - go get -u github.com/golang/lint/golint
  - go get -u golang.org/x/tools/cmd/cover
  - go get -u golang.org/x/tools/cmd/goimports
  - go get -u golang.org/x/tools/cmd/vet
  - go get -u golang.org/x/tools/cmd/oracle
  - go get -u sourcegraph.com/sqs/goreturns
  - go get -u github.com/nsf/gocode
  - appveyor DownloadFile https://atom.io/download/windows -FileName AtomSetup.exe
  - AtomSetup.exe /silent

# to run your custom scripts instead of automatic MSBuild
build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - SET PATH=%LOCALAPPDATA%\atom\bin;%GOPATH%\bin;%PATH%
  - apm clean
  - apm install autocomplete-plus
  - apm install
  - apm test

# to disable automatic tests
test: off

# to disable deployment
deploy: off
