#!/bin/sh
#
# dot
#
# `dot` handles installation, updates, things like that. Run it periodically
# to make sure you're on the latest and greatest.
export ZSH=$HOME/.dotfiles

# Set OS X defaults
$ZSH/osx/set-defaults.sh

# Upgrade homebrew
if test $(which brew)
then
	brew update
fi

# Install homebrew packages
$ZSH/homebrew/install.sh 2>&1
